// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterId        string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName         string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,4,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	TimestampSeconds int64                  `protobuf:"varint,5,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Region           string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	InstanceType     string                 `protobuf:"bytes,7,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Pods             []*PodMetric           `protobuf:"bytes,8,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ReportRequest) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *ReportRequest) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *ReportRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReportRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *ReportRequest) GetPods() []*PodMetric {
	if x != nil {
		return x.Pods
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PodMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata Context
	PodUid      string `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PidTgid     uint32 `protobuf:"varint,3,opt,name=pid_tgid,json=pidTgid,proto3" json:"pid_tgid,omitempty"`
	// Include namespace/pod name to help aggregator if K8s API is lagging,
	// but strictly spec just says identifiers.
	// "The agent must resolve destination IPs..." -> Agent does heavy lifting for network.
	// Let's keep namespace/name as they are cheap and useful.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName   string `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Compute Performance
	Cpu    *CpuMetrics    `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory *MemoryMetrics `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	// Cost-Aware Network
	Network *NetworkMetrics `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	// Storage I/O
	Storage       *StorageMetrics `protobuf:"bytes,9,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMetric) Reset() {
	*x = PodMetric{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMetric) ProtoMessage() {}

func (x *PodMetric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMetric.ProtoReflect.Descriptor instead.
func (*PodMetric) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PodMetric) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PodMetric) GetPidTgid() uint32 {
	if x != nil {
		return x.PidTgid
	}
	return 0
}

func (x *PodMetric) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodMetric) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodMetric) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *PodMetric) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *PodMetric) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *PodMetric) GetStorage() *StorageMetrics {
	if x != nil {
		return x.Storage
	}
	return nil
}

type CpuMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total nanoseconds in user space
	UsageUserNs uint64 `protobuf:"varint,1,opt,name=usage_user_ns,json=usageUserNs,proto3" json:"usage_user_ns,omitempty"`
	// Total nanoseconds in kernel space
	UsageKernelNs uint64 `protobuf:"varint,2,opt,name=usage_kernel_ns,json=usageKernelNs,proto3" json:"usage_kernel_ns,omitempty"`
	// Total run_delay (throttling) in nanoseconds
	ThrottlingNs uint64 `protobuf:"varint,3,opt,name=throttling_ns,json=throttlingNs,proto3" json:"throttling_ns,omitempty"`
	// K8s Requests (mCPU)
	RequestMillicores uint64 `protobuf:"varint,4,opt,name=request_millicores,json=requestMillicores,proto3" json:"request_millicores,omitempty"`
	// K8s Limits (mCPU)
	LimitMillicores uint64 `protobuf:"varint,5,opt,name=limit_millicores,json=limitMillicores,proto3" json:"limit_millicores,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CpuMetrics) GetUsageUserNs() uint64 {
	if x != nil {
		return x.UsageUserNs
	}
	return 0
}

func (x *CpuMetrics) GetUsageKernelNs() uint64 {
	if x != nil {
		return x.UsageKernelNs
	}
	return 0
}

func (x *CpuMetrics) GetThrottlingNs() uint64 {
	if x != nil {
		return x.ThrottlingNs
	}
	return 0
}

func (x *CpuMetrics) GetRequestMillicores() uint64 {
	if x != nil {
		return x.RequestMillicores
	}
	return 0
}

func (x *CpuMetrics) GetLimitMillicores() uint64 {
	if x != nil {
		return x.LimitMillicores
	}
	return 0
}

type MemoryMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resident Set Size (bytes)
	RssBytes uint64 `protobuf:"varint,1,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	// Major page faults
	PageFaultsMajor uint64 `protobuf:"varint,2,opt,name=page_faults_major,json=pageFaultsMajor,proto3" json:"page_faults_major,omitempty"`
	// K8s Requests (bytes)
	RequestBytes uint64 `protobuf:"varint,3,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	// K8s Limits (bytes)
	LimitBytes    uint64 `protobuf:"varint,4,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryMetrics) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *MemoryMetrics) GetPageFaultsMajor() uint64 {
	if x != nil {
		return x.PageFaultsMajor
	}
	return 0
}

func (x *MemoryMetrics) GetRequestBytes() uint64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *MemoryMetrics) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

type NetworkMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Throughput
	BytesSent     uint64 `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived uint64 `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Traffic Categorization (Egress Analyzer)
	EgressPublicBytes   uint64 `protobuf:"varint,3,opt,name=egress_public_bytes,json=egressPublicBytes,proto3" json:"egress_public_bytes,omitempty"`
	EgressCrossAzBytes  uint64 `protobuf:"varint,4,opt,name=egress_cross_az_bytes,json=egressCrossAzBytes,proto3" json:"egress_cross_az_bytes,omitempty"`
	EgressInternalBytes uint64 `protobuf:"varint,5,opt,name=egress_internal_bytes,json=egressInternalBytes,proto3" json:"egress_internal_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetrics) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NetworkMetrics) GetEgressPublicBytes() uint64 {
	if x != nil {
		return x.EgressPublicBytes
	}
	return 0
}

func (x *NetworkMetrics) GetEgressCrossAzBytes() uint64 {
	if x != nil {
		return x.EgressCrossAzBytes
	}
	return 0
}

func (x *NetworkMetrics) GetEgressInternalBytes() uint64 {
	if x != nil {
		return x.EgressInternalBytes
	}
	return 0
}

type StorageMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Throughput
	ReadBytes  uint64 `protobuf:"varint,1,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes uint64 `protobuf:"varint,2,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	// IOPS
	ReadOps  uint64 `protobuf:"varint,3,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`
	WriteOps uint64 `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`
	// Latency
	TotalLatencyNs uint64 `protobuf:"varint,5,opt,name=total_latency_ns,json=totalLatencyNs,proto3" json:"total_latency_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageMetrics) Reset() {
	*x = StorageMetrics{}
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetrics) ProtoMessage() {}

func (x *StorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetrics.ProtoReflect.Descriptor instead.
func (*StorageMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StorageMetrics) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *StorageMetrics) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *StorageMetrics) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *StorageMetrics) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

func (x *StorageMetrics) GetTotalLatencyNs() uint64 {
	if x != nil {
		return x.TotalLatencyNs
	}
	return 0
}

var File_internal_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_internal_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"#internal/proto/agent/v1/agent.proto\x12\bagent.v1\"\xa6\x02\n" +
	"\rReportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12+\n" +
	"\x11availability_zone\x18\x04 \x01(\tR\x10availabilityZone\x12+\n" +
	"\x11timestamp_seconds\x18\x05 \x01(\x03R\x10timestampSeconds\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12#\n" +
	"\rinstance_type\x18\a \x01(\tR\finstanceType\x12'\n" +
	"\x04pods\x18\b \x03(\v2\x13.agent.v1.PodMetricR\x04pods\"Q\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xdc\x02\n" +
	"\tPodMetric\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpid_tgid\x18\x03 \x01(\rR\apidTgid\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12&\n" +
	"\x03cpu\x18\x06 \x01(\v2\x14.agent.v1.CpuMetricsR\x03cpu\x12/\n" +
	"\x06memory\x18\a \x01(\v2\x17.agent.v1.MemoryMetricsR\x06memory\x122\n" +
	"\anetwork\x18\b \x01(\v2\x18.agent.v1.NetworkMetricsR\anetwork\x122\n" +
	"\astorage\x18\t \x01(\v2\x18.agent.v1.StorageMetricsR\astorage\"\xd7\x01\n" +
	"\n" +
	"CpuMetrics\x12\"\n" +
	"\rusage_user_ns\x18\x01 \x01(\x04R\vusageUserNs\x12&\n" +
	"\x0fusage_kernel_ns\x18\x02 \x01(\x04R\rusageKernelNs\x12#\n" +
	"\rthrottling_ns\x18\x03 \x01(\x04R\fthrottlingNs\x12-\n" +
	"\x12request_millicores\x18\x04 \x01(\x04R\x11requestMillicores\x12)\n" +
	"\x10limit_millicores\x18\x05 \x01(\x04R\x0flimitMillicores\"\x9e\x01\n" +
	"\rMemoryMetrics\x12\x1b\n" +
	"\trss_bytes\x18\x01 \x01(\x04R\brssBytes\x12*\n" +
	"\x11page_faults_major\x18\x02 \x01(\x04R\x0fpageFaultsMajor\x12#\n" +
	"\rrequest_bytes\x18\x03 \x01(\x04R\frequestBytes\x12\x1f\n" +
	"\vlimit_bytes\x18\x04 \x01(\x04R\n" +
	"limitBytes\"\xed\x01\n" +
	"\x0eNetworkMetrics\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x04R\rbytesReceived\x12.\n" +
	"\x13egress_public_bytes\x18\x03 \x01(\x04R\x11egressPublicBytes\x121\n" +
	"\x15egress_cross_az_bytes\x18\x04 \x01(\x04R\x12egressCrossAzBytes\x122\n" +
	"\x15egress_internal_bytes\x18\x05 \x01(\x04R\x13egressInternalBytes\"\xb2\x01\n" +
	"\x0eStorageMetrics\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x01(\x04R\n" +
	"writeBytes\x12\x19\n" +
	"\bread_ops\x18\x03 \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\x04 \x01(\x04R\bwriteOps\x12(\n" +
	"\x10total_latency_ns\x18\x05 \x01(\x04R\x0etotalLatencyNs2H\n" +
	"\tCollector\x12;\n" +
	"\x06Report\x12\x17.agent.v1.ReportRequest\x1a\x18.agent.v1.ReportResponseBNZLgithub.com/clustercost/clustercost-dashboard/internal/proto/agent/v1;agentv1b\x06proto3"

var (
	file_internal_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_internal_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_internal_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_agent_v1_agent_proto_rawDesc), len(file_internal_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_internal_proto_agent_v1_agent_proto_rawDescData
}

var file_internal_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_agent_v1_agent_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: agent.v1.ReportRequest
	(*ReportResponse)(nil), // 1: agent.v1.ReportResponse
	(*PodMetric)(nil),      // 2: agent.v1.PodMetric
	(*CpuMetrics)(nil),     // 3: agent.v1.CpuMetrics
	(*MemoryMetrics)(nil),  // 4: agent.v1.MemoryMetrics
	(*NetworkMetrics)(nil), // 5: agent.v1.NetworkMetrics
	(*StorageMetrics)(nil), // 6: agent.v1.StorageMetrics
}
var file_internal_proto_agent_v1_agent_proto_depIdxs = []int32{
	2, // 0: agent.v1.ReportRequest.pods:type_name -> agent.v1.PodMetric
	3, // 1: agent.v1.PodMetric.cpu:type_name -> agent.v1.CpuMetrics
	4, // 2: agent.v1.PodMetric.memory:type_name -> agent.v1.MemoryMetrics
	5, // 3: agent.v1.PodMetric.network:type_name -> agent.v1.NetworkMetrics
	6, // 4: agent.v1.PodMetric.storage:type_name -> agent.v1.StorageMetrics
	0, // 5: agent.v1.Collector.Report:input_type -> agent.v1.ReportRequest
	1, // 6: agent.v1.Collector.Report:output_type -> agent.v1.ReportResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_v1_agent_proto_init() }
func file_internal_proto_agent_v1_agent_proto_init() {
	if File_internal_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_agent_v1_agent_proto_rawDesc), len(file_internal_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_internal_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_v1_agent_proto = out.File
	file_internal_proto_agent_v1_agent_proto_goTypes = nil
	file_internal_proto_agent_v1_agent_proto_depIdxs = nil
}
