// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterId        string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName         string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,4,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	TimestampSeconds int64                  `protobuf:"varint,5,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Region           string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	InstanceType     string                 `protobuf:"bytes,7,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Pods             []*PodMetric           `protobuf:"bytes,8,rep,name=pods,proto3" json:"pods,omitempty"`
	Nodes            []*NodeMetric          `protobuf:"bytes,9,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsReportRequest) Reset() {
	*x = MetricsReportRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReportRequest) ProtoMessage() {}

func (x *MetricsReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReportRequest.ProtoReflect.Descriptor instead.
func (*MetricsReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsReportRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsReportRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *MetricsReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *MetricsReportRequest) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *MetricsReportRequest) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *MetricsReportRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MetricsReportRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *MetricsReportRequest) GetPods() []*PodMetric {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *MetricsReportRequest) GetNodes() []*NodeMetric {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NetworkReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterId        string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName         string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,4,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	TimestampSeconds int64                  `protobuf:"varint,5,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Region           string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	InstanceType     string                 `protobuf:"bytes,7,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	// Optimization: Dictionary Encoding
	Endpoints          []*NetworkEndpoint          `protobuf:"bytes,10,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	CompactConnections []*CompactNetworkConnection `protobuf:"bytes,11,rep,name=compact_connections,json=compactConnections,proto3" json:"compact_connections,omitempty"`
	// Deprecated: Use endpoints + compact_connections
	Connections   []*NetworkConnection `protobuf:"bytes,8,rep,name=connections,proto3" json:"connections,omitempty"`
	Pods          []*PodMetric         `protobuf:"bytes,9,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkReportRequest) Reset() {
	*x = NetworkReportRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkReportRequest) ProtoMessage() {}

func (x *NetworkReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkReportRequest.ProtoReflect.Descriptor instead.
func (*NetworkReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkReportRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *NetworkReportRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NetworkReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NetworkReportRequest) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *NetworkReportRequest) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *NetworkReportRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NetworkReportRequest) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *NetworkReportRequest) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkReportRequest) GetCompactConnections() []*CompactNetworkConnection {
	if x != nil {
		return x.CompactConnections
	}
	return nil
}

func (x *NetworkReportRequest) GetConnections() []*NetworkConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *NetworkReportRequest) GetPods() []*PodMetric {
	if x != nil {
		return x.Pods
	}
	return nil
}

type CompactNetworkConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIndex      uint32                 `protobuf:"varint,1,opt,name=src_index,json=srcIndex,proto3" json:"src_index,omitempty"` // Index into request.endpoints
	DstIndex      uint32                 `protobuf:"varint,2,opt,name=dst_index,json=dstIndex,proto3" json:"dst_index,omitempty"` // Index into request.endpoints
	Protocol      uint32                 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived uint64                 `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	EgressClass   string                 `protobuf:"bytes,6,opt,name=egress_class,json=egressClass,proto3" json:"egress_class,omitempty"`
	DstKind       string                 `protobuf:"bytes,8,opt,name=dst_kind,json=dstKind,proto3" json:"dst_kind,omitempty"`
	ServiceMatch  string                 `protobuf:"bytes,9,opt,name=service_match,json=serviceMatch,proto3" json:"service_match,omitempty"`
	IsEgress      bool                   `protobuf:"varint,10,opt,name=is_egress,json=isEgress,proto3" json:"is_egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactNetworkConnection) Reset() {
	*x = CompactNetworkConnection{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactNetworkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactNetworkConnection) ProtoMessage() {}

func (x *CompactNetworkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactNetworkConnection.ProtoReflect.Descriptor instead.
func (*CompactNetworkConnection) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CompactNetworkConnection) GetSrcIndex() uint32 {
	if x != nil {
		return x.SrcIndex
	}
	return 0
}

func (x *CompactNetworkConnection) GetDstIndex() uint32 {
	if x != nil {
		return x.DstIndex
	}
	return 0
}

func (x *CompactNetworkConnection) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *CompactNetworkConnection) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *CompactNetworkConnection) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *CompactNetworkConnection) GetEgressClass() string {
	if x != nil {
		return x.EgressClass
	}
	return ""
}

func (x *CompactNetworkConnection) GetDstKind() string {
	if x != nil {
		return x.DstKind
	}
	return ""
}

func (x *CompactNetworkConnection) GetServiceMatch() string {
	if x != nil {
		return x.ServiceMatch
	}
	return ""
}

func (x *CompactNetworkConnection) GetIsEgress() bool {
	if x != nil {
		return x.IsEgress
	}
	return false
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PodMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata Context
	PodUid      string `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	PidTgid     uint32 `protobuf:"varint,3,opt,name=pid_tgid,json=pidTgid,proto3" json:"pid_tgid,omitempty"`
	// Include namespace/pod name to help aggregator if K8s API is lagging,
	// but strictly spec just says identifiers.
	// "The agent must resolve destination IPs..." -> Agent does heavy lifting for network.
	// Let's keep namespace/name as they are cheap and useful.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName   string `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Compute Performance
	Cpu    *CpuMetrics    `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory *MemoryMetrics `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	// Cost-Aware Network
	Network *NetworkMetrics `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	// Storage I/O
	Storage       *StorageMetrics `protobuf:"bytes,9,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMetric) Reset() {
	*x = PodMetric{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMetric) ProtoMessage() {}

func (x *PodMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMetric.ProtoReflect.Descriptor instead.
func (*PodMetric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PodMetric) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodMetric) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PodMetric) GetPidTgid() uint32 {
	if x != nil {
		return x.PidTgid
	}
	return 0
}

func (x *PodMetric) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodMetric) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodMetric) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *PodMetric) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *PodMetric) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *PodMetric) GetStorage() *StorageMetrics {
	if x != nil {
		return x.Storage
	}
	return nil
}

type CpuMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// K8s Requests (mCPU)
	RequestMillicores uint64 `protobuf:"varint,4,opt,name=request_millicores,json=requestMillicores,proto3" json:"request_millicores,omitempty"`
	// K8s Limits (mCPU)
	LimitMillicores uint64 `protobuf:"varint,5,opt,name=limit_millicores,json=limitMillicores,proto3" json:"limit_millicores,omitempty"`
	// Usage (mCPU)
	UsageMillicores uint64 `protobuf:"varint,6,opt,name=usage_millicores,json=usageMillicores,proto3" json:"usage_millicores,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CpuMetrics) GetRequestMillicores() uint64 {
	if x != nil {
		return x.RequestMillicores
	}
	return 0
}

func (x *CpuMetrics) GetLimitMillicores() uint64 {
	if x != nil {
		return x.LimitMillicores
	}
	return 0
}

func (x *CpuMetrics) GetUsageMillicores() uint64 {
	if x != nil {
		return x.UsageMillicores
	}
	return 0
}

type MemoryMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resident Set Size (bytes)
	RssBytes uint64 `protobuf:"varint,1,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	// Major page faults
	PageFaultsMajor uint64 `protobuf:"varint,2,opt,name=page_faults_major,json=pageFaultsMajor,proto3" json:"page_faults_major,omitempty"`
	// K8s Requests (bytes)
	RequestBytes uint64 `protobuf:"varint,3,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	// K8s Limits (bytes)
	LimitBytes    uint64 `protobuf:"varint,4,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryMetrics) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *MemoryMetrics) GetPageFaultsMajor() uint64 {
	if x != nil {
		return x.PageFaultsMajor
	}
	return 0
}

func (x *MemoryMetrics) GetRequestBytes() uint64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *MemoryMetrics) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

type NetworkMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Throughput
	BytesSent     uint64 `protobuf:"varint,1,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived uint64 `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Traffic Categorization (Egress Analyzer)
	EgressPublicBytes   uint64 `protobuf:"varint,3,opt,name=egress_public_bytes,json=egressPublicBytes,proto3" json:"egress_public_bytes,omitempty"`
	EgressCrossAzBytes  uint64 `protobuf:"varint,4,opt,name=egress_cross_az_bytes,json=egressCrossAzBytes,proto3" json:"egress_cross_az_bytes,omitempty"`
	EgressInternalBytes uint64 `protobuf:"varint,5,opt,name=egress_internal_bytes,json=egressInternalBytes,proto3" json:"egress_internal_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkMetrics) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkMetrics) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NetworkMetrics) GetEgressPublicBytes() uint64 {
	if x != nil {
		return x.EgressPublicBytes
	}
	return 0
}

func (x *NetworkMetrics) GetEgressCrossAzBytes() uint64 {
	if x != nil {
		return x.EgressCrossAzBytes
	}
	return 0
}

func (x *NetworkMetrics) GetEgressInternalBytes() uint64 {
	if x != nil {
		return x.EgressInternalBytes
	}
	return 0
}

type NetworkConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *NetworkEndpoint       `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           *NetworkEndpoint       `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Protocol      uint32                 `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived uint64                 `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	EgressClass   string                 `protobuf:"bytes,6,opt,name=egress_class,json=egressClass,proto3" json:"egress_class,omitempty"`
	DstKind       string                 `protobuf:"bytes,8,opt,name=dst_kind,json=dstKind,proto3" json:"dst_kind,omitempty"`
	ServiceMatch  string                 `protobuf:"bytes,9,opt,name=service_match,json=serviceMatch,proto3" json:"service_match,omitempty"`
	IsEgress      bool                   `protobuf:"varint,10,opt,name=is_egress,json=isEgress,proto3" json:"is_egress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConnection) Reset() {
	*x = NetworkConnection{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnection) ProtoMessage() {}

func (x *NetworkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnection.ProtoReflect.Descriptor instead.
func (*NetworkConnection) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkConnection) GetSrc() *NetworkEndpoint {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *NetworkConnection) GetDst() *NetworkEndpoint {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *NetworkConnection) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *NetworkConnection) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetworkConnection) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NetworkConnection) GetEgressClass() string {
	if x != nil {
		return x.EgressClass
	}
	return ""
}

func (x *NetworkConnection) GetDstKind() string {
	if x != nil {
		return x.DstKind
	}
	return ""
}

func (x *NetworkConnection) GetServiceMatch() string {
	if x != nil {
		return x.ServiceMatch
	}
	return ""
}

func (x *NetworkConnection) GetIsEgress() bool {
	if x != nil {
		return x.IsEgress
	}
	return false
}

type NodeMetric struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NodeName                 string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	CpuUsageMillicores       uint64                 `protobuf:"varint,2,opt,name=cpu_usage_millicores,json=cpuUsageMillicores,proto3" json:"cpu_usage_millicores,omitempty"`
	MemoryUsageBytes         uint64                 `protobuf:"varint,3,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	CapacityCpuMillicores    uint64                 `protobuf:"varint,4,opt,name=capacity_cpu_millicores,json=capacityCpuMillicores,proto3" json:"capacity_cpu_millicores,omitempty"`
	CapacityMemoryBytes      uint64                 `protobuf:"varint,5,opt,name=capacity_memory_bytes,json=capacityMemoryBytes,proto3" json:"capacity_memory_bytes,omitempty"`
	AllocatableCpuMillicores uint64                 `protobuf:"varint,6,opt,name=allocatable_cpu_millicores,json=allocatableCpuMillicores,proto3" json:"allocatable_cpu_millicores,omitempty"`
	AllocatableMemoryBytes   uint64                 `protobuf:"varint,7,opt,name=allocatable_memory_bytes,json=allocatableMemoryBytes,proto3" json:"allocatable_memory_bytes,omitempty"`
	RequestedCpuMillicores   uint64                 `protobuf:"varint,8,opt,name=requested_cpu_millicores,json=requestedCpuMillicores,proto3" json:"requested_cpu_millicores,omitempty"`
	RequestedMemoryBytes     uint64                 `protobuf:"varint,9,opt,name=requested_memory_bytes,json=requestedMemoryBytes,proto3" json:"requested_memory_bytes,omitempty"`
	// Total throttled CPU time from cgroup cpu.stat (ns).
	ThrottlingNs uint64 `protobuf:"varint,10,opt,name=throttling_ns,json=throttlingNs,proto3" json:"throttling_ns,omitempty"`
	// Cost-Aware Network (Host traffic)
	Network       *NetworkMetrics `protobuf:"bytes,11,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetric) Reset() {
	*x = NodeMetric{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetric) ProtoMessage() {}

func (x *NodeMetric) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetric.ProtoReflect.Descriptor instead.
func (*NodeMetric) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *NodeMetric) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeMetric) GetCpuUsageMillicores() uint64 {
	if x != nil {
		return x.CpuUsageMillicores
	}
	return 0
}

func (x *NodeMetric) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *NodeMetric) GetCapacityCpuMillicores() uint64 {
	if x != nil {
		return x.CapacityCpuMillicores
	}
	return 0
}

func (x *NodeMetric) GetCapacityMemoryBytes() uint64 {
	if x != nil {
		return x.CapacityMemoryBytes
	}
	return 0
}

func (x *NodeMetric) GetAllocatableCpuMillicores() uint64 {
	if x != nil {
		return x.AllocatableCpuMillicores
	}
	return 0
}

func (x *NodeMetric) GetAllocatableMemoryBytes() uint64 {
	if x != nil {
		return x.AllocatableMemoryBytes
	}
	return 0
}

func (x *NodeMetric) GetRequestedCpuMillicores() uint64 {
	if x != nil {
		return x.RequestedCpuMillicores
	}
	return 0
}

func (x *NodeMetric) GetRequestedMemoryBytes() uint64 {
	if x != nil {
		return x.RequestedMemoryBytes
	}
	return 0
}

func (x *NodeMetric) GetThrottlingNs() uint64 {
	if x != nil {
		return x.ThrottlingNs
	}
	return 0
}

func (x *NodeMetric) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

type NetworkEndpoint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ip               string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName          string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	NodeName         string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AvailabilityZone string                 `protobuf:"bytes,5,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	Services         []*ServiceRef          `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	DnsName          string                 `protobuf:"bytes,7,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkEndpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkEndpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkEndpoint) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *NetworkEndpoint) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NetworkEndpoint) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *NetworkEndpoint) GetServices() []*ServiceRef {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *NetworkEndpoint) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

type ServiceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRef) Reset() {
	*x = ServiceRef{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRef) ProtoMessage() {}

func (x *ServiceRef) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRef.ProtoReflect.Descriptor instead.
func (*ServiceRef) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StorageMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Throughput
	ReadBytes  uint64 `protobuf:"varint,1,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes uint64 `protobuf:"varint,2,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	// IOPS
	ReadOps  uint64 `protobuf:"varint,3,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`
	WriteOps uint64 `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`
	// Latency
	TotalLatencyNs uint64 `protobuf:"varint,5,opt,name=total_latency_ns,json=totalLatencyNs,proto3" json:"total_latency_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageMetrics) Reset() {
	*x = StorageMetrics{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetrics) ProtoMessage() {}

func (x *StorageMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetrics.ProtoReflect.Descriptor instead.
func (*StorageMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StorageMetrics) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *StorageMetrics) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *StorageMetrics) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *StorageMetrics) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

func (x *StorageMetrics) GetTotalLatencyNs() uint64 {
	if x != nil {
		return x.TotalLatencyNs
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\xd9\x02\n" +
	"\x14MetricsReportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12+\n" +
	"\x11availability_zone\x18\x04 \x01(\tR\x10availabilityZone\x12+\n" +
	"\x11timestamp_seconds\x18\x05 \x01(\x03R\x10timestampSeconds\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12#\n" +
	"\rinstance_type\x18\a \x01(\tR\finstanceType\x12'\n" +
	"\x04pods\x18\b \x03(\v2\x13.agent.v1.PodMetricR\x04pods\x12*\n" +
	"\x05nodes\x18\t \x03(\v2\x14.agent.v1.NodeMetricR\x05nodes\"\xfa\x03\n" +
	"\x14NetworkReportRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12+\n" +
	"\x11availability_zone\x18\x04 \x01(\tR\x10availabilityZone\x12+\n" +
	"\x11timestamp_seconds\x18\x05 \x01(\x03R\x10timestampSeconds\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12#\n" +
	"\rinstance_type\x18\a \x01(\tR\finstanceType\x127\n" +
	"\tendpoints\x18\n" +
	" \x03(\v2\x19.agent.v1.NetworkEndpointR\tendpoints\x12S\n" +
	"\x13compact_connections\x18\v \x03(\v2\".agent.v1.CompactNetworkConnectionR\x12compactConnections\x12=\n" +
	"\vconnections\x18\b \x03(\v2\x1b.agent.v1.NetworkConnectionR\vconnections\x12'\n" +
	"\x04pods\x18\t \x03(\v2\x13.agent.v1.PodMetricR\x04pods\"\xb6\x02\n" +
	"\x18CompactNetworkConnection\x12\x1b\n" +
	"\tsrc_index\x18\x01 \x01(\rR\bsrcIndex\x12\x1b\n" +
	"\tdst_index\x18\x02 \x01(\rR\bdstIndex\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x04R\rbytesReceived\x12!\n" +
	"\fegress_class\x18\x06 \x01(\tR\vegressClass\x12\x19\n" +
	"\bdst_kind\x18\b \x01(\tR\adstKind\x12#\n" +
	"\rservice_match\x18\t \x01(\tR\fserviceMatch\x12\x1b\n" +
	"\tis_egress\x18\n" +
	" \x01(\bR\bisEgress\"Q\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xdc\x02\n" +
	"\tPodMetric\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bpid_tgid\x18\x03 \x01(\rR\apidTgid\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12&\n" +
	"\x03cpu\x18\x06 \x01(\v2\x14.agent.v1.CpuMetricsR\x03cpu\x12/\n" +
	"\x06memory\x18\a \x01(\v2\x17.agent.v1.MemoryMetricsR\x06memory\x122\n" +
	"\anetwork\x18\b \x01(\v2\x18.agent.v1.NetworkMetricsR\anetwork\x122\n" +
	"\astorage\x18\t \x01(\v2\x18.agent.v1.StorageMetricsR\astorage\"\x91\x01\n" +
	"\n" +
	"CpuMetrics\x12-\n" +
	"\x12request_millicores\x18\x04 \x01(\x04R\x11requestMillicores\x12)\n" +
	"\x10limit_millicores\x18\x05 \x01(\x04R\x0flimitMillicores\x12)\n" +
	"\x10usage_millicores\x18\x06 \x01(\x04R\x0fusageMillicores\"\x9e\x01\n" +
	"\rMemoryMetrics\x12\x1b\n" +
	"\trss_bytes\x18\x01 \x01(\x04R\brssBytes\x12*\n" +
	"\x11page_faults_major\x18\x02 \x01(\x04R\x0fpageFaultsMajor\x12#\n" +
	"\rrequest_bytes\x18\x03 \x01(\x04R\frequestBytes\x12\x1f\n" +
	"\vlimit_bytes\x18\x04 \x01(\x04R\n" +
	"limitBytes\"\xed\x01\n" +
	"\x0eNetworkMetrics\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x01 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x04R\rbytesReceived\x12.\n" +
	"\x13egress_public_bytes\x18\x03 \x01(\x04R\x11egressPublicBytes\x121\n" +
	"\x15egress_cross_az_bytes\x18\x04 \x01(\x04R\x12egressCrossAzBytes\x122\n" +
	"\x15egress_internal_bytes\x18\x05 \x01(\x04R\x13egressInternalBytes\"\xcf\x02\n" +
	"\x11NetworkConnection\x12+\n" +
	"\x03src\x18\x01 \x01(\v2\x19.agent.v1.NetworkEndpointR\x03src\x12+\n" +
	"\x03dst\x18\x02 \x01(\v2\x19.agent.v1.NetworkEndpointR\x03dst\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\rR\bprotocol\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x04R\rbytesReceived\x12!\n" +
	"\fegress_class\x18\x06 \x01(\tR\vegressClass\x12\x19\n" +
	"\bdst_kind\x18\b \x01(\tR\adstKind\x12#\n" +
	"\rservice_match\x18\t \x01(\tR\fserviceMatch\x12\x1b\n" +
	"\tis_egress\x18\n" +
	" \x01(\bR\bisEgress\"\xb6\x04\n" +
	"\n" +
	"NodeMetric\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x120\n" +
	"\x14cpu_usage_millicores\x18\x02 \x01(\x04R\x12cpuUsageMillicores\x12,\n" +
	"\x12memory_usage_bytes\x18\x03 \x01(\x04R\x10memoryUsageBytes\x126\n" +
	"\x17capacity_cpu_millicores\x18\x04 \x01(\x04R\x15capacityCpuMillicores\x122\n" +
	"\x15capacity_memory_bytes\x18\x05 \x01(\x04R\x13capacityMemoryBytes\x12<\n" +
	"\x1aallocatable_cpu_millicores\x18\x06 \x01(\x04R\x18allocatableCpuMillicores\x128\n" +
	"\x18allocatable_memory_bytes\x18\a \x01(\x04R\x16allocatableMemoryBytes\x128\n" +
	"\x18requested_cpu_millicores\x18\b \x01(\x04R\x16requestedCpuMillicores\x124\n" +
	"\x16requested_memory_bytes\x18\t \x01(\x04R\x14requestedMemoryBytes\x12#\n" +
	"\rthrottling_ns\x18\n" +
	" \x01(\x04R\fthrottlingNs\x122\n" +
	"\anetwork\x18\v \x01(\v2\x18.agent.v1.NetworkMetricsR\anetwork\"\xf1\x01\n" +
	"\x0fNetworkEndpoint\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12+\n" +
	"\x11availability_zone\x18\x05 \x01(\tR\x10availabilityZone\x120\n" +
	"\bservices\x18\x06 \x03(\v2\x14.agent.v1.ServiceRefR\bservices\x12\x19\n" +
	"\bdns_name\x18\a \x01(\tR\adnsName\">\n" +
	"\n" +
	"ServiceRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\x0eStorageMetrics\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x01(\x04R\n" +
	"writeBytes\x12\x19\n" +
	"\bread_ops\x18\x03 \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\x04 \x01(\x04R\bwriteOps\x12(\n" +
	"\x10total_latency_ns\x18\x05 \x01(\x04R\x0etotalLatencyNs2\xa1\x01\n" +
	"\tCollector\x12I\n" +
	"\rReportMetrics\x12\x1e.agent.v1.MetricsReportRequest\x1a\x18.agent.v1.ReportResponse\x12I\n" +
	"\rReportNetwork\x12\x1e.agent.v1.NetworkReportRequest\x1a\x18.agent.v1.ReportResponseB7Z5clustercost-agent-k8s/internal/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_v1_agent_proto_goTypes = []any{
	(*MetricsReportRequest)(nil),     // 0: agent.v1.MetricsReportRequest
	(*NetworkReportRequest)(nil),     // 1: agent.v1.NetworkReportRequest
	(*CompactNetworkConnection)(nil), // 2: agent.v1.CompactNetworkConnection
	(*ReportResponse)(nil),           // 3: agent.v1.ReportResponse
	(*PodMetric)(nil),                // 4: agent.v1.PodMetric
	(*CpuMetrics)(nil),               // 5: agent.v1.CpuMetrics
	(*MemoryMetrics)(nil),            // 6: agent.v1.MemoryMetrics
	(*NetworkMetrics)(nil),           // 7: agent.v1.NetworkMetrics
	(*NetworkConnection)(nil),        // 8: agent.v1.NetworkConnection
	(*NodeMetric)(nil),               // 9: agent.v1.NodeMetric
	(*NetworkEndpoint)(nil),          // 10: agent.v1.NetworkEndpoint
	(*ServiceRef)(nil),               // 11: agent.v1.ServiceRef
	(*StorageMetrics)(nil),           // 12: agent.v1.StorageMetrics
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	4,  // 0: agent.v1.MetricsReportRequest.pods:type_name -> agent.v1.PodMetric
	9,  // 1: agent.v1.MetricsReportRequest.nodes:type_name -> agent.v1.NodeMetric
	10, // 2: agent.v1.NetworkReportRequest.endpoints:type_name -> agent.v1.NetworkEndpoint
	2,  // 3: agent.v1.NetworkReportRequest.compact_connections:type_name -> agent.v1.CompactNetworkConnection
	8,  // 4: agent.v1.NetworkReportRequest.connections:type_name -> agent.v1.NetworkConnection
	4,  // 5: agent.v1.NetworkReportRequest.pods:type_name -> agent.v1.PodMetric
	5,  // 6: agent.v1.PodMetric.cpu:type_name -> agent.v1.CpuMetrics
	6,  // 7: agent.v1.PodMetric.memory:type_name -> agent.v1.MemoryMetrics
	7,  // 8: agent.v1.PodMetric.network:type_name -> agent.v1.NetworkMetrics
	12, // 9: agent.v1.PodMetric.storage:type_name -> agent.v1.StorageMetrics
	10, // 10: agent.v1.NetworkConnection.src:type_name -> agent.v1.NetworkEndpoint
	10, // 11: agent.v1.NetworkConnection.dst:type_name -> agent.v1.NetworkEndpoint
	7,  // 12: agent.v1.NodeMetric.network:type_name -> agent.v1.NetworkMetrics
	11, // 13: agent.v1.NetworkEndpoint.services:type_name -> agent.v1.ServiceRef
	0,  // 14: agent.v1.Collector.ReportMetrics:input_type -> agent.v1.MetricsReportRequest
	1,  // 15: agent.v1.Collector.ReportNetwork:input_type -> agent.v1.NetworkReportRequest
	3,  // 16: agent.v1.Collector.ReportMetrics:output_type -> agent.v1.ReportResponse
	3,  // 17: agent.v1.Collector.ReportNetwork:output_type -> agent.v1.ReportResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
